# Generated by Django 5.2.4 on 2025-08-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recurringtransactiontemplate_savingsgoal_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
